#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.2.0.{build}

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
build_script:
  ps: .\MakeRelease.ps1

# build script will run tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing entire folder as a zip archive
  - path: out
    name: Bugsnag.$(APPVEYOR_BUILD_VERSION)
    type: zip

  # pushing all *.nupkg files in directory
  - path: out\*.nupkg
    name: Bugsnag.$(APPVEYOR_BUILD_VERSION)
